//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(schema_name = "public_data", table_name = "generate_stream")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub create_time: DateTimeWithTimeZone,
    pub completed: Option<bool>,
    pub complete_time: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
